---
- name: Configure machine for development work
  hosts: localhost
  connection: local

##### Core tools that are missing from Kubuntu

- import_playbook: sdkman/core.yml


# Final tasks
- import_playbook: java/core.yml

### Customizations
- import_playbook: bash/core.yml
- import_playbook: bash/post.yml
- import_playbook: kde.yml
